# Generated by Django 4.2.2 on 2023-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0002_rename_orderlocation_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FilePathField(default='default.png', path='static/Pizza/Menu', recursive=True),
        ),
    ]
