# Generated by Django 4.2.2 on 2023-07-07 19:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0003_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Order Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
