# Generated by Django 4.2.2 on 2023-07-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0005_remove_order_order_date_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='dateTime',
        ),
    ]
