# Generated by Django 4.2.2 on 2023-07-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0006_rename_time_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='static/Pizza/Menu/'),
        ),
    ]
