# Generated by Django 4.2.2 on 2023-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0007_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='toppings',
            field=models.ManyToManyField(blank=True, db_table='ItemToppingJoin', to='Pizza.topping'),
        ),
        migrations.AlterField(
            model_name='itemorderjoin',
            name='toppings',
            field=models.ManyToManyField(blank=True, db_table='ItemToppingOrderJoin', to='Pizza.topping'),
        ),
    ]
