# Generated by Django 4.2.2 on 2023-07-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0008_alter_item_toppings_alter_itemorderjoin_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='Pizza/static/Pizza/Menu/'),
        ),
    ]
