# Generated by Django 4.2.2 on 2023-07-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pizza', '0009_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FilePathField(default='default.png', path='Pizza/static/Pizza/Menu/'),
        ),
    ]
